---
title: Simulated Hospital Encounter Data Dashboard
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(plotly)

year <- '2020'
hospital <- 'rhode island hospital'

data <- read_csv('simulated_patient_data.csv') %>% 
  mutate(start_date = as_date(start)) %>% 
  filter(year(start)==year, name == hospital)

visits_by_date <- data %>% 
  count(name,start_date)

visits_by_reason <- data %>% 
           count(reasondescription)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Encounters by Date

```{r}
visits_by_date <- visits_by_date %>% mutate(wday = wday(start_date, label=T))

plot_ly(visits_by_date,x = ~start_date, y= ~n,
        text = ~paste("Total Encounters: ", n, '<br>Date', start_date, '<br>Weekday: ', wday))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Top Encounter reason

```{r}
visits_by_reason %>% top_n(10, n) %>% drop_na() %>% 
  ggplot()+
  geom_col(aes(y=reorder(reasondescription, n), x=n), fill='mediumblue')+
  theme_classic()+
  xlab('Number of Encounters')+
  ylab('') 

```

### Top 10 Encounter Types

```{r}
data %>% count(description) %>% drop_na() %>%  top_n(10,n) %>% 
  ggplot()+
  geom_col(aes(y=reorder(description, n), x=n), fill='darkgreen')+
  theme_classic()+
  xlab('Number of Encounters')+
  ylab('')
```

