---
title: "Buidling Blocks"
output: html_notebook
---

The code snippets below contain the building blocks for the content used to populate a dashboard, report, and API throughout these exercises. 

Start by running each code snippet. What do you need to change to view the same information for Tesla? (Ticker: `TSLA`)? Try the stock ticker for your favorite company.


```{r setup}
library(tidyverse)
library(tidyquant)
library(timetk)
library(highcharter)
library(DT)

price <- tq_get('GOOG', from = "2018-01-01") %>% 
  mutate(change = close - open)
```

```{r data-table}

DT::datatable(price, rownames = FALSE, options = list(order = list(list(0, 'desc')))) %>% 
  formatCurrency(c('open', 'high', 'low', 'close', 'adjusted', 'change')) %>% 
  formatDate(c('date')) %>%
  formatStyle('volume', 
    background = styleColorBar(price$volume, 'steelblue')
  ) %>% 
  formatStyle(
    'change', 
    color = styleInterval(c(0), c('maroon', 'darkgreen'))
  )
```

```{r volatility}
volatility <- price %>% 
    select(date, adjusted) %>% 
    mutate(returns = (log(adjusted) - log(lag(adjusted)))) %>%
    na.omit() %>% 
    summarize(volatility = var(returns)) %>% 
    pull(volatility)

sprintf('%g%%', round(volatility*100,2))
```



```{r chart}
xts_price <- tk_xts(price)
colnames(xts_price) <- paste0('GOOG.', colnames(xts_price))

highchart(type = "stock") %>% 
  hc_add_series(xts_price, type = "candlestick")
```